"""initial schema

Revision ID: 383ffe6f31d2
Revises: 
Create Date: 2026-08-12 14:02:20.725294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '383ffe6f31d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_account_number'), 'customers', ['account_number'], unique=True)
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.create_table('customer_cases',
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('BILLING', 'PAYMENT', 'METER_READING', 'POWER_OUTAGE', 'CONNECTION', 'SERVICE_REQUEST', 'COMPLAINT', 'ACCOUNT_UPDATE', 'OTHER', name='case_category'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='case_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='case_priority'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_cases_case_number'), 'customer_cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_customer_cases_customer_id'), 'customer_cases', ['customer_id'], unique=False)
    op.create_table('ai_analysis',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('BILLING', 'PAYMENT', 'METER_READING', 'POWER_OUTAGE', 'CONNECTION', 'SERVICE_REQUEST', 'COMPLAINT', 'ACCOUNT_UPDATE', 'OTHER', name='case_category'), nullable=False),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'CONCERNED', 'FRUSTRATED', 'ANGRY', name='sentiment'), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('ai_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='case_priority'), nullable=False),
    sa.Column('key_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions_taken', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pending_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['customer_cases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_case_id'), 'ai_analysis', ['case_id'], unique=False)
    op.create_table('ai_analysis_runs',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('input_message_count', sa.Integer(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='ai_analysis_run_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['customer_cases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_runs_case_id'), 'ai_analysis_runs', ['case_id'], unique=False)
    op.create_table('conversations',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.Enum('CUSTOMER', 'AGENT', name='sender_type'), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.Enum('CHAT', 'EMAIL', 'PHONE', 'IMPORTED', name='conversation_channel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['customer_cases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_case_id'), 'conversations', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_case_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_ai_analysis_runs_case_id'), table_name='ai_analysis_runs')
    op.drop_table('ai_analysis_runs')
    op.drop_index(op.f('ix_ai_analysis_case_id'), table_name='ai_analysis')
    op.drop_table('ai_analysis')
    op.drop_index(op.f('ix_customer_cases_customer_id'), table_name='customer_cases')
    op.drop_index(op.f('ix_customer_cases_case_number'), table_name='customer_cases')
    op.drop_table('customer_cases')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_index(op.f('ix_customers_account_number'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
